import React, { useEffect, useState } from "react";

import { SelectedCardWrapper,SelectedImage,SelectedInfo ,BicycleContent,BicycleTextContent} from "./SelectedCard.styled";
import { Button } from "antd";

import BicycleHeader from "./BicycleHeader";
import Card from "antd/es/card/Card";
import {  useParams } from "react-router-dom";
import "../SelectedCard/selectedCard.css"
import { getBicycles,getBicycleById } from "../../service/api";
import {useDispatch} from "react-redux";
import { actionsType } from "../../Store/store";
import store from "../../Store/store";
const text =`A bicycle is a means of transportation consisting
 of two wheels, a frame, pedals, and handlebars. 
 It operates through human power generated by pedaling. 
 Bicycles are a popular mode of physical activity and transportation, 
ideal for various terrains and purposes, from urban commuting to recreational riding.`

const SelectedCard =()=>{
  const dispatch = useDispatch()


  const [bicycles,setBicycles ] = useState([]);

  
  useEffect(()=>{
    getBicycles().then(bicycles =>{
        setBicycles(bicycles)
    })
  },[])
 

   const {id} = useParams();
   const bicycleId = parseInt(id)
    const bicycleData = bicycles.find(b => b.id === Number(bicycleId) )
    if (!bicycleData) {
      
      return <div>Loading...</div>;
    }
   
    function addItemToCart() {
        dispatch({
            type: actionsType.addToCart,
            bicycleToAdd: bicycleData
        })
    }
    return(
       <SelectedCardWrapper>

           <BicycleHeader />
           <BicycleContent>
                <Card
                    hoverable 
                    cover = {
                        <img style={{width:400, height: 300}} src = {bicycleData.image}/>
                    }
                    style={{width:400,height:400}}
                    > 
                      <h2 style={{textAlign:'center'}}>
                        {bicycleData.title}
                      </h2>
              </Card>
              <div>
                    <div className="sel_item_description">
                      <p>{text}</p>
                    </div>
                    <div className="sel_item_price" >
                         <h2>Price: {bicycleData.price} $ </h2>
                      
                        <Button className="add_to_cart" onClick={addItemToCart}>Add to cart</Button>
                    </div>
              </div>
            </BicycleContent>
      </SelectedCardWrapper>

    )
}

export default SelectedCard